# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_figure_calc', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfc_id', models.IntegerField()),
                ('barcode', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='figures',
            field=models.ManyToManyField(to='anime.Figure'),
        ),
    ]
