# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20151209_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='barcode',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
